# Generated by Django 4.2.6 on 2023-11-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_post_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="titletag",
            field=models.CharField(default="sleety.io", max_length=255),
        ),
    ]
