# Generated by Django 4.2.6 on 2023-11-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_remove_post_category_post_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ManyToManyField(default="uncategorized", to="blog.category"),
        ),
    ]
