# Generated by Django 4.2.6 on 2023-11-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_remove_post_category_post_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category_slug",
            field=models.SlugField(blank=True),
        ),
    ]
