# Generated by Django 4.2.6 on 2023-11-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0013_rename_category_snippet_post_snippet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="snippet",
            field=models.CharField(max_length=255),
        ),
    ]
