# Generated by Django 4.2.6 on 2023-11-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0014_alter_post_snippet"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="header_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
