# Generated by Django 4.2.7 on 2023-11-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("country", models.CharField(max_length=64, verbose_name="country")),
                ("lat", models.FloatField(verbose_name="lat")),
                ("lon", models.FloatField(verbose_name="lon")),
                ("base", models.IntegerField(verbose_name="base")),
                ("mid", models.IntegerField(verbose_name="mid")),
                ("top", models.IntegerField(verbose_name="top")),
            ],
        ),
    ]
