# Generated by Django 4.2.7 on 2023-11-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snow_forecast", "0002_alter_resort_options_alter_resort_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="resort",
            name="snowfall_total",
            field=models.FloatField(
                blank=True, null=True, verbose_name="3-day snowfall total"
            ),
        ),
    ]
