# Generated by Django 4.2.7 on 2023-11-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snow_forecast", "0003_resort_snowfall_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resort",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=100, null=True, verbose_name="name"
            ),
        ),
    ]
