# Generated by Django 4.2.7 on 2023-11-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snow_forecast", "0005_remove_resort_snowfall_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="resort",
            name="continent",
            field=models.CharField(
                default="null", max_length=64, verbose_name="continent"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resort",
            name="state_province",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="state_province"
            ),
        ),
        migrations.AlterField(
            model_name="resort",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
    ]
