# Generated by Django 4.2.7 on 2023-11-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snow_forecast", "0006_resort_continent_resort_state_province_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resort",
            name="timezone",
            field=models.CharField(blank=True, max_length=64, verbose_name="timezone"),
        ),
    ]
