# Generated by Django 4.2.6 on 2023-11-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snow_forecast", "0007_resort_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resort",
            name="country",
            field=models.CharField(
                choices=[("Canada", "Canada"), ("USA", "Usa")],
                max_length=20,
                verbose_name="country",
            ),
        ),
    ]
