# Generated by Django 4.2.6 on 2023-11-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snow_forecast", "0008_alter_resort_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resort",
            name="country",
            field=models.CharField(max_length=20, verbose_name="country"),
        ),
    ]
