# Generated by Django 4.2.6 on 2023-12-27 20:16

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("snow_forecast", "0009_alter_resort_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="resort",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="Aspen", editable=False, populate_from="name", unique=True
            ),
            preserve_default=False,
        ),
    ]
