# Generated by Django 4.2.6 on 2023-12-27 20:18

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("snow_forecast", "0010_resort_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resort",
            name="slug",
            field=autoslug.fields.AutoSlugField(editable=False, populate_from="name"),
        ),
    ]
