# Generated by Django 4.2.6 on 2023-12-27 20:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("snow_forecast", "0011_alter_resort_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resort",
            name="slug",
        ),
    ]
